title: Jordan Jambazov
email: jordan.jambazov@gmail.com
description: >-
  Software Developer. Proud dad of three kids. All opinions are wrong, but
  some are useful.
baseurl: ""
url: "https://jordanjambazov.com"
twitter_username: jordanjambazov
github_username:  jordanjambazov

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
